name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check toolchain version
      run:  rustup show 
    - name: Check the formatting
      run: cargo fmt -- --check 
    - name: Lint it
      run: cargo clippy
    - name: Build all
      run: RUSTFLAGS="--deny warnings" cargo build --all-targets
    - name: Run tests
      run: cargo test
