version: '3'

services:
  mysql:
    image: 'mysql:8.0.26'
    container_name: 'mysql'
    expose:
      - '3306'
    ports:
      - '13306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'qwer1234'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'qwer1234'
      MYSQL_DATABASE: 'ta_db'
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --sql-mode=NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES
